version: 2
jobs:
  build-python35:
    docker:
      - image: python:3.5
    working_directory: ~/your_project
    steps:
      - checkout
      - run: pip install .
      # TODO: add better tests
      - run: numerai docker copy-example
      - run: test -e predict.py
  build-python36:
    docker:
      - image: python:3.6
    working_directory: ~/your_project
    steps:
      - checkout
      - run: pip install .
      # TODO: add better tests
      - run: numerai docker copy-example
      - run: test -e predict.py
  build-python37:
    docker:
      - image: python:3.6
    working_directory: ~/your_project
    steps:
      - checkout
      - run: pip install .
      # TODO: add better tests
      - run: numerai docker copy-example
      - run: test -e predict.py

workflows:
  version: 2
  build:
    jobs:
      # - build-python35 TODO add this back in
      - build-python36
      - build-python37
